name: Upload cloudfree
on:
  push:
    branches:
      - main()
  # Actions タブから手動でワークフローを実行できるようにします
  workflow_dispatch:

jobs:
  deploy:
    name: FTP upload to cloudfree
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
          local-dir: ./dist/
